#pragma once

enum ExceptionTypes {
    EXCEPTION_INFO_MAIN     = 0x1,
    EXCEPTION_INFO_GPR      = 0x2,
    EXCEPTION_INFO_GPRMAP   = 0x4,
    EXCEPTION_INFO_SRR0MAP  = 0x8,
    EXCEPTION_INFO_FPR      = 0x10,
    EXCEPTION_INFO_TRACE    = 0x20,
    EXCEPTION_INFO_ALL      = 0x3F,
    EXCEPTION_INFO_DEFAULT  = EXCEPTION_INFO_MAIN | EXCEPTION_INFO_TRACE,
};
