name: Build Binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache-1
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-cache-33

      - name: Download devkitPPC r33
        if: steps.cache-1.outputs.cache-hit != 'true'
        run: |
          mkdir cache && cd cache
          wget "https://wii.leseratte10.de/devkitPro/file.php/devkitPPC-r33-1-linux.pkg.tar.xz"
          cd ..

      - name: Extract devkitPPC
        run: |
          tar -xf cache/devkitPPC-r33-1-linux.pkg.tar.xz opt/devkitpro/devkitPPC --strip-components=1

      - name: Install PyELFTools
        run: |
          pip install pyelftools

      - name: Compile
        run: |
          cp -r $(pwd)/devkitpro/devkitPPC devkitPPC/
          cd src
          python3 make.py

      - name: Upload Result
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
            args: src/bin/*.bin
